<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'title'=>"Lavazza MAVİ Amabile – x100 kapsül",
                'keywords'=>"kahve",
                'image'=>"1669621024.jpg",
                'description'=>"description",
                'category_id'=> 6,
                'detail'=>"product detail",
                'price'=>35,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-amabile-capsules",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>7,
                'sale_price'=>35,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"AFES GRAN ESPRESSO X6 Kg",
                'keywords'=>"kahve",
                'image'=>"1672741700.jpg",
                'description'=>"AFES GRAN ESPRESSO",
                'category_id'=> 8,
                'detail'=>" AFES GRAN ESPRESSO",
                'price'=>150,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"afes-gran-espresso",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>7,
                'sale_price'=>150,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Ahşap kahve karıştırıcı ",
                'keywords'=>"kahve karıştırıcı",
                'image'=>"1669621065.jpg",
                'description'=>"description",
                'category_id'=> 4,
                'detail'=>"product detail",
                'price'=>100,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"ahsap-kahve-karıstırıcı",
                'status'=>"True",
                'is_sale'=>"Yes",
                'sale'=>2,
                'sale_price'=>98,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Kahve makinesi – IDOLA – bir Modo Mio",
                'keywords'=>"kahve",
                'image'=>"1669621102.jpg",
                'description'=>"description",
                'category_id'=> 9,
                'detail'=>"product detail",
                'price'=>500,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"kahve-makineleri",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>0,
                'sale_price'=>500,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Kahve makinesi – Jolie Plus – bir Modo Mio",
                'keywords'=>"kahve",
                'image'=>"1669621140.jpg",
                'description'=>"description",
                'category_id'=> 9,
                'detail'=>"product detail",
                'price'=>200,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"kahve-makineleri",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>0,
                'sale_price'=>200,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"LAVAZZA BLUE kırmızı meyveler x 15 kapsül",
                'keywords'=>"kahve",
                'image'=>"1669621211.jpg",
                'description'=>"description",
                'category_id'=>10,
                'detail'=>"product detail",
                'price'=>50,
                'quantity'=>35,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-amabile-capsulesss",
                'status'=>"True",
                'is_sale'=>"Yes",
                'sale'=>7,
                'sale_price'=>46.5,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Lavazza Espresso Point AL LIMONE limon x50 kapsül",
                'keywords'=>"kahve",
                'image'=>"1672741732.jpg",
                'description'=>"description",
                'category_id'=> 11,
                'detail'=>"product detail",
                'price'=>200,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-espresso-point-al-limone-citron-x50-capsules",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>7,
                'sale_price'=>50,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"LAVAZZA BLUE Şeftali Çayı x15 Kapsül",
                'keywords'=>"kahve",
                'image'=>"1669621274.jpg",
                'description'=>"description",
                'category_id'=>10,
                'detail'=>"product detail",
                'price'=>60,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-amabile-seftali",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>7,
                'sale_price'=>60,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Lavazza DEK CREMOSO A Modo Mio x 32 kapsül",
                'keywords'=>"kahve",
                'image'=>"1672209263.jpg",
                'description'=>"description",
                'category_id'=> 7,
                'detail'=>"product detail",
                'price'=>250,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-amabile-capsules",
                'status'=>"True",
                'is_sale'=>"Yes",
                'sale'=>20,
                'sale_price'=>200,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"LAVAZZA MAVİ NANE x 15 Kapsül",
                'keywords'=>"kahve",
                'image'=>"1672741754.jpg",
                'description'=>"description",
                'category_id'=> 10,
                'detail'=>"product detail",
                'price'=>60,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-amabile-capsules",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>20,
                'sale_price'=>60,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Lavazza Crema Aroma Gran Espresso Point x100 kapsül",
                'keywords'=>"kahve",
                'image'=>"1672741787.jpg",
                'description'=>"description",
                'category_id'=> 12,
                'detail'=>"product detail",
                'price'=>60,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-creama-aroma-capsules",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>20,
                'sale_price'=>60,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
            [
                'title'=>"Lavazza Espresso Point Bevanda Bianca Süt ",
                'keywords'=>"kahve",
                'image'=>"1672741811.jpg",
                'description'=>"description",
                'category_id'=> 12,
                'detail'=>"product detail",
                'price'=>100,
                'quantity'=>37,
                'minquantity'=>1,
                'tax'=>18,
                'user_id'=>1,
                'slug'=>"lavazza-blue-espresso-point-sut-capsul",
                'status'=>"True",
                'is_sale'=>"No",
                'sale'=>20,
                'sale_price'=>100,
                'main_category_id'=>0,
                'created_at'=>now(),
                'updated_at'=>now(),
            ],
        ]);
    }
}
